project:
  type: website
  output-dir: docs

website:
  title: "Jess Wallingford"
  favicon: img/favicon.png
  
  navbar:
    pinned: true
    logo: /img/logo.png
    
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - research.qmd
      - text: "CV"
        href: cv/index.qmd

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

