project:
  type: website
  output-dir: docs

website:
  google-analytics: G-57MNCT6C1F
  title: "JESSICA K. WALLINGFORD"
  favicon: img/favicon.png
  
  page-footer:
    center: |
      Contact me: jessica.wallingford@tufts.edu
    left: |
      <span style="color: #FFFFFF">&copy; 2024 Jess Wallingford</span>
    right: | 
      Made with <a href="https://quarto.org" target="_blank">Quarto</a>\
      <span style="color: #FDA172">Last modified: March 2025</span>
    border: true
    background: "#353A3F"    
    foreground: white
  
  navbar:
    pinned: true
    
    left:
      - href: index.qmd
        text: HOME
      - about.qmd
      - research.qmd
      - text: "CV"
        href: cv/index.qmd

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: visual


