project:
  type: website
  output-dir: docs

website:
  google-analytics: G-57MNCT6C1F
  title: "JESSICA K. WALLINGFORD"
  favicon: img/favicon.png
  
  navbar:
    pinned: true
    
    left:
      - href: index.qmd
        text: HOME
      - about.qmd
      - research.qmd
      - text: "CV"
        href: cv/index.qmd

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: visual

